Repository ThisIsComedy/nodam-nodam_frontend, pull requests merged in 2023-11, with the labels that each got.

#12 Feat/#8
  package.json
  public/assets/global/HomeIndicator.png
  public/assets/global/IPhone14_Inner.png
  public/assets/global/error.png
  public/assets/global/iPhone14.png
  public/assets/global/nodamnodamlogo.png
  public/assets/global/nodamnodamsymbol.png
  public/assets/global/notion.png
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/index.css
  src/index.tsx
  src/layout/Aside/Aside.tsx
  src/layout/Layout.tsx
  src/layout/Screen/Screen.tsx
  src/logo.svg
  src/pages/Home/Home.tsx
  src/react-app-env.d.ts
  src/setupTests.ts
  src/styles/color.tsx
  src/styles/font.tsx
  src/styles/global.tsx
  yarn.lock
Labels: 💡 feature

#13 feat: 푸터 퍼블리싱
  public/assets/footer/home_active.png
  public/assets/footer/home_default.png
  public/assets/footer/profile_active.png
  public/assets/footer/profile_default.png
  public/assets/footer/ranking_active.png
  public/assets/footer/ranking_default.png
  public/assets/footer/record_active.png
  public/assets/footer/record_default.png
  src/components/Footer/Footer.tsx
  src/components/Footer/GNBButton.tsx
  src/layout/Aside/Aside.tsx
  src/layout/Layout.tsx
  src/pages/Home/Home.tsx
Labels: 💡 feature

#14 fix: 필요없는 props(bgColor) 삭제
  src/components/Footer/Footer.tsx
  src/pages/Home/Home.tsx
Labels: 💡 feature

#16 CI/CD 설정 파일 변경
  .github/workflows/cicd.yml
  Dockerfile
Labels: 🐳 deploy

#18 Feat/#3
  package.json
  public/assets/home/check.png
  public/assets/home/nodamnodamlogo_gray.png
  src/components/BoxContainer/BoxContainer.tsx
  src/components/GrassChart/GrassCell.tsx
  src/components/GrassChart/GrassChart.tsx
  src/components/KnowHowBox/KnowHowBox.tsx
  src/components/RateBox/RateBox.tsx
  src/components/ThreeDaysCheckBox/CheckButton.tsx
  src/components/ThreeDaysCheckBox/ThreeDaysCheckBox.tsx
  src/layout/Aside/Aside.tsx
  src/pages/Home/Home.tsx
Labels: 💡 feature

#19 하단 GNB 라우팅 처리
  src/components/Footer/Footer.tsx
Labels: 💡 feature

#21 Feat/#6
  public/assets/global/nodamSampleImage.png
  src/App.tsx
  src/components/RankingGroup/DefaultRankingGroup.tsx
  src/components/RankingGroup/PodiumBox.tsx
  src/components/RankingGroup/Top3RankingGroup.tsx
  src/pages/Ranking/Ranking.tsx
Labels: 💡 feature

#24 Feat/#23
  public/assets/404/nodam404.png
  src/App.tsx
  src/pages/NotFound/NotFound.tsx
Labels: 💡 feature

#25 Feat/#2
  .github/workflows/cicd.yml
  .gitignore
  package.json
  public/assets/badge/badge_0.png
  public/assets/badge/badge_1.png
  public/assets/badge/badge_2.png
  public/assets/badge/badge_3.png
  public/assets/login/loading.gif
  public/assets/register/left_arrow.svg
  src/App.tsx
  src/apis/index.ts
  src/apis/instance.ts
  src/apis/recoil/state.ts
  src/apis/recoil/type/index.ts
  src/apis/tokenRefresh.ts
  src/components/Badge/Badge.tsx
  src/components/Register/index.tsx
  src/components/atoms/LargeButton.tsx
  src/components/atoms/TwoButton.tsx
  src/config/index.ts
  src/pages/Home/Home.tsx
  src/pages/Login/index.tsx
  src/pages/Onboarding/index.tsx
  src/pages/register/index.tsx
  src/pages/register/types.ts
  src/pages/register/validate.ts
  yarn.lock
Labels: 💡 feature

#27 로그아웃 기능 구현
  src/apis/index.ts
  src/components/Register/index.tsx
  src/pages/Profile/Profile.tsx
  src/pages/register/store/state.ts
  src/pages/register/store/type/index.ts
Labels: 💡 feature

#33 Feat/#32
  src/components/Register/index.tsx
  src/pages/Home/Home.tsx
  src/pages/Onboarding/index.tsx
Labels: 🐞 bug fix
